export enum PaymentMode {
	'ZPSS' = 'ZPSS',
	'CASH' = 'CASH',
	'BOB_MBOB' = 'BOB_MBOB',
	'BDB_EPAY' = 'BDB_EPAY',
	'BNB_MPAY' = 'BNB_MPAY',
	'DK_BANK' = 'DK_BANK',
	'DPNB_DRUKPAY' = 'DPNB_DRUKPAY',
	'TBANK_TPAY' = 'TBANK_TPAY',
}
export enum BookingStatus {
	'PENDING' = 'PENDING',
	'CONFIRMED' = 'CONFIRMED',
	'CANCELLED' = 'CANCELLED',
	'EXPIRED' = 'EXPIRED',
}
export enum BookingType {
	'ONLINE' = 'ONLINE',
	'COUNTER' = 'COUNTER',
}

export enum RefundReason {
	CUSTOMER_REQUEST = 'CUSTOMER_REQUEST',
	SCREENING_CANCELLED = 'SCREENING_CANCELLED',
	TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
	DUPLICATE_PAYMENT = 'DUPLICATE_PAYMENT',
	SYSTEM_ERROR = 'SYSTEM_ERROR',
	FRAUD_PREVENTION = 'FRAUD_PREVENTION',
}
